### ISSUE TITLE
运行main报错

### ISSUE THREAD

**Issue by Dummy0121** [zhmou/zhmou.github.io#1]
楼主您好，请问我在运行您的代码时候，epoch2次之后报错：FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/FD004_iteration1_best_score.pth.tar'   不知道具体怎么回事？谢谢

**Comment by zhmou** [comment]
首先呢，你的这个issue发错地方了。那个代码的仓库是在这里：https://github.com/zhmou/Turbofan-engine-RUL-prediction
这个仓库是个github pages，不要发在这里。
其次就你目前提供的信息而言，我推测应该是路径错误，具体来说应该是这个函数中：
https://github.com/zhmou/Turbofan-engine-RUL-prediction/blob/81a69876f14c73d6d490fa4deb4d9c29d912aee3/train.py#L57
它要保存训练好的参数，但是找不到对应的路径，你应该在代码文件夹中新建一个名为“checkpoints”的文件夹，这样每个iteration中结果最佳的模型权重就会保存在checkpoints文件夹下。

如果后续还有其它问题，可以考虑附上整个Trackback的截图补充说明，方便分析一些。
这个代码写了有一段时间也忘得有点多了，抱歉。
祝顺利~

**Comment by Dummy0121** [comment]
好的好的 非常非常感谢
| |
江昌
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月10日 23:03 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhmou/zhmou.github.io] 运行main报错 (Issue #1) |

首先呢，你的这个issue发错地方了。那个代码的仓库是在这里：https://github.com/zhmou/Turbofan-engine-RUL-prediction
这个仓库是个github pages，不要发在这里。
其次就你目前提供的信息而言，我推测应该是路径错误，具体来说应该是这个函数中：
https://github.com/zhmou/Turbofan-engine-RUL-prediction/blob/81a69876f14c73d6d490fa4deb4d9c29d912aee3/train.py#L57
它要保存训练好的参数，但是找不到对应的路径，你应该在代码文件夹中新建一个名为“checkpoints”的文件夹，这样每个iteration中结果最佳的模型权重就会保存在checkpoints文件夹下。

如果后续还有其它问题，可以考虑附上整个Trackback的截图补充说明，方便分析一些。
这个代码写了有一段时间也忘得有点多了，抱歉。
祝顺利~
