### ISSUE TITLE
Hi, I have two questions for you

### ISSUE THREAD

**Issue by clongwei** [zhmou/zhmou.github.io#2]
The first question is whether running_loss = 0 on line 38 of train.py should be outside the if loop.
The second question is can the best score and rmse results for each training be extracted as shown in the code? The original author doesn't seem to have done that.
I am a beginner, the question may be incorrect, please understand.

**Comment by zhmou** [comment]
第一个问题，你是指的[这里](https://github.com/zhmou/Turbofan-engine-RUL-prediction/blob/78cdc81cab7408dbad64c8bd315feef8eba5f4a7/train.py#L37)吗？
前面的打印信息基本上解释了，最后打印的是每<code>print_every</code>个batch的loss之和的平均值，所以打印完了才清零。你要是想在每个batch都打印一次loss可以考虑把<code>print_every</code>设为1
第二个问题，每次训练都会保存（32个Epoch里面）最佳的score和rmse结果，我测试了10次（iteration）训练过程，结果都存在列表里，主要是复现一下原作者在论文里面的那个结果。

我也有个问题，为啥issue要发在这里，而不是直接在[对应仓库](https://github.com/zhmou/Turbofan-engine-RUL-prediction/issues)发？

**Comment by clongwei** [comment]
第二个问题，我想问的是在一般情况也可以这样操作吗？就是取训练过程中最好的结果。
关于你的问题，我是点[README.md](https://github.com/zhmou/Turbofan-engine-RUL-prediction#readme)最下面的链接进来的。我也不知道(⊙_⊙)？

**Comment by zhmou** [comment]
草，原来是我链接给错了(x
我个人认为：
在每次训练的不同Epoch的过程中一般都是选最好的结果，或者说，是训练到收敛后的结果。因为训练到后边可能会出现过拟合之类的现象，所以导致模型的表现会呈现出一开始随着训练Epoch的增加而升高，然后略微下降的情况，这时候取最好结果无可厚非。像是网上的yolo这些模型啦，在自己训练的时候也会存个最佳权重，因为实际上并不是训练得越久就是越好的。

然后由于这个最好的结果一定程度上是由随机种子决定的，为了避免或者说减轻这种影响，所以在n个随机初始化权重的训练中，取这些训练的n个最佳结果，然后画个箱型图之类的，才能证明提出的方法确实优于以前的方法（而不是随机初始化权重的影响）

**Comment by clongwei** [comment]
要是像您在[README.md](https://github.com/zhmou/Turbofan-engine-RUL-prediction#readme)最后提到的，n个最佳结果跨度比较大。假如在我的结果中，其中有部分结果较好，但是存在部分结果效果较差，能不能体现方法的优越性呢。0.o

**Comment by zhmou** [comment]
这个问题自然就看怎么自圆其说让审稿人信服喽，2333

**Comment by clongwei** [comment]
哈哈哈，感谢您的解答

**Comment by clongwei** [comment]
发现这篇论文的FD004的score是五千多，我看最近的论文都已经降到一千出头了
